add_includedirs("include")
-- target("demo2_server")
--     add_files("main.cpp")
--     set_kind("binary")
-- target("demo2_client")
--     add_files("client_main.cpp")
--     set_kind("binary")
target("demo2_advance_server")
    add_files("advance_main.cpp")
    set_kind("binary")
    add_defines("SHMSERVER")
target("demo2_advance_client")
    add_files("advance_client_main.cpp")
    set_kind("binary")
